# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmyservice.proto\x12\tmyservice\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x92\x01\n\x0b\x41uthService\x12<\n\x05Login\x12\x17.myservice.LoginRequest\x1a\x18.myservice.LoginResponse\"\x00\x12\x45\n\x08Register\x12\x1a.myservice.RegisterRequest\x1a\x1b.myservice.RegisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=30
  _LOGINREQUEST._serialized_end=80
  _LOGINRESPONSE._serialized_start=82
  _LOGINRESPONSE._serialized_end=131
  _REGISTERREQUEST._serialized_start=133
  _REGISTERREQUEST._serialized_end=186
  _REGISTERRESPONSE._serialized_start=188
  _REGISTERRESPONSE._serialized_end=240
  _AUTHSERVICE._serialized_start=243
  _AUTHSERVICE._serialized_end=389
# @@protoc_insertion_point(module_scope)
